stages:
  - build

# Cache the templates and build-context to speed things up
cache:
  key: ${CI_COMMIT_REF_SLUG} # i.e. master
  paths:
    - ./faas-cli
    - ./template

# Build the whole stack using only the faas-cli
docker-build:
  stage: build
  image: docker:dind
  script:
    - apk add --no-cache git
    - if [ -f "./faas-cli" ] ; then cp ./faas-cli /usr/local/bin/faas-cli || 0 ; fi
    - if [ ! -f "/usr/local/bin/faas-cli" ] ; then apk add --no-cache curl git && curl -sSL cli.openfaas.com | sh && chmod +x /usr/local/bin/faas-cli && /usr/local/bin/faas-cli template pull && faas-cli template pull https://github.com/openfaas-incubator/golang-http-template.git && cp /usr/local/bin/faas-cli ./faas-cli ; fi

    # Build Docker image
    - /usr/local/bin/faas-cli build -f openfaas-qr.yml --tag=sha --parallel=2

    # Login & Push Docker image to private repo
    - echo -n "$CI_DOCKER_PASSWORD" | docker login --username $CI_DOCKER_USER --password-stdin
    - /usr/local/bin/faas-cli push -f openfaas-qr.yml --tag=sha
    - echo -n "$CI_OPENFAAS_PASSWORD" | /usr/local/bin/faas-cli login --gateway http://192.168.178.231 --username admin --password-stdin

    # Deploy function from private repo
    - /usr/local/bin/faas-cli deploy -f openfaas-qr.yml --gateway http://192.168.178.231 --tag=sha --send-registry-auth

  only:
    - master